// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/jflex/jflexSpec.jflex


/* user code */
package jflex;
//import java_cup.sym;
import java_cup.runtime.*;
import cup.*;
import symbolTable.*;
import java.util.ArrayList;
import fileManager.*;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\1\7\1\10\1\11\2\0\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\11\25"+
    "\3\0\1\26\3\0\32\27\1\30\1\0\1\31\1\0"+
    "\1\32\1\0\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\27\1\44\1\45\1\27\1\46"+
    "\1\47\2\27\1\50\1\51\1\52\1\53\1\27\1\54"+
    "\1\27\1\55\1\27\1\56\1\57\1\60\7\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\16\1\17\1\20\1\21\1\22\12\20\1\23\1\24"+
    "\1\25\4\0\1\26\1\16\1\27\13\20\1\30\7\20"+
    "\1\31\1\32\1\0\1\26\7\20\1\33\2\20\1\34"+
    "\1\35\6\20\1\36\4\20\1\37\1\40\1\41\5\20"+
    "\1\42\1\43\1\20\1\44\1\45\1\20\1\46\1\47"+
    "\1\50\3\20\1\51\1\20\1\52\1\53\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\142\0\61\0\223\0\61\0\61"+
    "\0\304\0\61\0\61\0\61\0\61\0\61\0\61\0\61"+
    "\0\365\0\u0126\0\u0157\0\u0188\0\u01b9\0\61\0\61\0\u01ea"+
    "\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372"+
    "\0\u03a3\0\61\0\61\0\61\0\u03d4\0\u0405\0\u0436\0\u0467"+
    "\0\u0498\0\u04c9\0\61\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be"+
    "\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u01b9\0\u0715"+
    "\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\61\0\61"+
    "\0\u086c\0\61\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992"+
    "\0\u09c3\0\u01b9\0\u09f4\0\u0a25\0\u01b9\0\u01b9\0\u0a56\0\u0a87"+
    "\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\61\0\u0b7c\0\u0bad\0\u0bde"+
    "\0\u0c0f\0\u01b9\0\u01b9\0\u01b9\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3"+
    "\0\u0d04\0\u01b9\0\u01b9\0\u0d35\0\u01b9\0\u01b9\0\u0d66\0\u01b9"+
    "\0\u01b9\0\u01b9\0\u0d97\0\u0dc8\0\u0df9\0\u01b9\0\u0e2a\0\u01b9"+
    "\0\u01b9\0\u01b9\0\u01b9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\4\1\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\2\1\30\1\31\1\32\1\25\1\33\1\34"+
    "\2\25\1\35\4\25\1\36\1\37\1\40\1\25\1\41"+
    "\1\25\1\42\1\43\1\44\63\0\1\3\64\0\1\45"+
    "\15\0\2\45\1\0\1\45\3\0\23\45\32\0\1\46"+
    "\3\0\23\46\21\0\1\47\42\0\2\50\4\0\53\50"+
    "\22\0\1\51\1\0\1\52\1\23\61\0\1\53\56\0"+
    "\2\25\1\0\1\25\2\0\24\25\27\0\2\25\1\0"+
    "\1\25\2\0\16\25\1\54\5\25\27\0\2\25\1\0"+
    "\1\25\2\0\5\25\1\55\7\25\1\56\1\57\5\25"+
    "\27\0\2\25\1\0\1\25\2\0\1\25\1\60\6\25"+
    "\1\61\13\25\27\0\2\25\1\0\1\25\2\0\13\25"+
    "\1\62\1\63\7\25\27\0\2\25\1\0\1\25\2\0"+
    "\1\25\1\64\11\25\1\65\1\25\1\66\6\25\27\0"+
    "\2\25\1\0\1\25\2\0\6\25\1\67\5\25\1\70"+
    "\7\25\27\0\2\25\1\0\1\25\2\0\5\25\1\71"+
    "\16\25\27\0\2\25\1\0\1\25\2\0\20\25\1\72"+
    "\1\25\1\73\1\25\27\0\2\25\1\0\1\25\2\0"+
    "\10\25\1\74\5\25\1\75\5\25\27\0\2\25\1\0"+
    "\1\25\2\0\10\25\1\76\13\25\11\0\1\45\1\0"+
    "\1\77\13\0\2\45\1\0\1\45\3\0\23\45\16\0"+
    "\1\100\53\0\1\47\7\0\1\101\5\0\2\47\1\0"+
    "\1\47\3\0\23\47\27\0\1\102\60\0\2\51\57\0"+
    "\2\52\57\0\2\25\1\0\1\25\2\0\16\25\1\103"+
    "\5\25\27\0\2\25\1\0\1\25\2\0\7\25\1\104"+
    "\14\25\27\0\2\25\1\0\1\25\2\0\15\25\1\105"+
    "\6\25\27\0\2\25\1\0\1\25\2\0\5\25\1\106"+
    "\16\25\27\0\2\25\1\0\1\25\2\0\17\25\1\107"+
    "\4\25\27\0\2\25\1\0\1\25\2\0\1\25\1\110"+
    "\22\25\27\0\2\25\1\0\1\25\2\0\17\25\1\111"+
    "\4\25\27\0\2\25\1\0\1\25\2\0\4\25\1\112"+
    "\17\25\27\0\2\25\1\0\1\25\2\0\13\25\1\113"+
    "\10\25\27\0\2\25\1\0\1\25\2\0\15\25\1\114"+
    "\6\25\27\0\2\25\1\0\1\25\2\0\16\25\1\115"+
    "\5\25\27\0\2\25\1\0\1\25\2\0\20\25\1\116"+
    "\3\25\27\0\2\25\1\0\1\25\2\0\20\25\1\117"+
    "\3\25\27\0\2\25\1\0\1\25\2\0\16\25\1\120"+
    "\5\25\27\0\2\25\1\0\1\25\2\0\11\25\1\121"+
    "\12\25\27\0\2\25\1\0\1\25\2\0\5\25\1\122"+
    "\16\25\27\0\2\25\1\0\1\25\2\0\21\25\1\123"+
    "\2\25\27\0\2\25\1\0\1\25\2\0\11\25\1\124"+
    "\12\25\26\0\1\125\61\0\2\25\1\0\1\25\2\0"+
    "\1\25\1\126\22\25\27\0\2\25\1\0\1\25\2\0"+
    "\11\25\1\127\12\25\27\0\2\25\1\0\1\25\2\0"+
    "\13\25\1\130\10\25\27\0\2\25\1\0\1\25\2\0"+
    "\1\25\1\131\22\25\27\0\2\25\1\0\1\25\2\0"+
    "\5\25\1\132\16\25\27\0\2\25\1\0\1\25\2\0"+
    "\16\25\1\133\5\25\27\0\2\25\1\0\1\25\2\0"+
    "\5\25\1\134\16\25\27\0\2\25\1\0\1\25\2\0"+
    "\17\25\1\135\4\25\27\0\2\25\1\0\1\25\2\0"+
    "\1\25\1\136\22\25\27\0\2\25\1\0\1\25\2\0"+
    "\21\25\1\137\2\25\27\0\2\25\1\0\1\25\2\0"+
    "\11\25\1\140\12\25\27\0\2\25\1\0\1\25\2\0"+
    "\20\25\1\141\3\25\27\0\2\25\1\0\1\25\2\0"+
    "\14\25\1\142\7\25\27\0\2\25\1\0\1\25\2\0"+
    "\5\25\1\143\16\25\27\0\2\25\1\0\1\25\2\0"+
    "\13\25\1\144\10\25\27\0\2\25\1\0\1\25\2\0"+
    "\23\25\1\145\27\0\2\25\1\0\1\25\2\0\14\25"+
    "\1\146\7\25\27\0\2\25\1\0\1\25\2\0\5\25"+
    "\1\147\16\25\27\0\2\25\1\0\1\25\2\0\12\25"+
    "\1\150\11\25\27\0\2\25\1\0\1\25\2\0\5\25"+
    "\1\151\16\25\27\0\2\25\1\0\1\25\2\0\20\25"+
    "\1\152\3\25\27\0\2\25\1\0\1\25\2\0\16\25"+
    "\1\153\5\25\27\0\2\25\1\0\1\25\2\0\14\25"+
    "\1\154\7\25\27\0\2\25\1\0\1\25\2\0\3\25"+
    "\1\155\20\25\27\0\2\25\1\0\1\25\2\0\5\25"+
    "\1\156\16\25\27\0\2\25\1\0\1\25\2\0\1\25"+
    "\1\157\22\25\27\0\2\25\1\0\1\25\2\0\14\25"+
    "\1\160\7\25\27\0\2\25\1\0\1\25\2\0\7\25"+
    "\1\161\14\25\27\0\2\25\1\0\1\25\2\0\10\25"+
    "\1\162\13\25\27\0\2\25\1\0\1\25\2\0\14\25"+
    "\1\163\7\25\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3675];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\1\1\2\11\1\1\7\11"+
    "\5\1\2\11\12\1\3\11\4\0\2\1\1\11\23\1"+
    "\2\11\1\0\1\11\22\1\1\11\36\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  StringBuilder string = new StringBuilder();
  public ArrayList<Token> tokens = new ArrayList<>();
  public SymbolTableManager newManager = new SymbolTableManager();
  public int scope = 0;
  private Symbol symbol(int type) {
    if (type == 26) {
      increaseScope();
    } else if (type == 27) {
      decreaseScope();
    }
    return new Symbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }

  private void tokenInfo(String token, String val) {
    String info = token + " > " + val + " < ";
    System.out.print(info);
  }

  private void saveToken(int symbol, String value) {
    if (symbol != 43) {
      Token newToken = new Token(symbol, value);
      tokens.add(newToken);
      String tokenInfo = "[ " + sym.terminalNames[newToken.getSymbol()] + " ] " + newToken.getSymbolName();
      writeTokensToFile(tokenInfo);
    } else {
      Token newToken = new Token(symbol, value, this.scope);
      tokens.add(newToken);
      String tokenInfo = "[ " + sym.terminalNames[newToken.getSymbol()] + " " + 
        newToken.getTokenId() + " ] " + newToken.getSymbolName() + " - Found in symbol table: " + newToken.getSymbolTable();
      writeTokensToFile(tokenInfo);
      // After creating the ID token, we save it to the symbol table with its attributes...
    }
  }

  private void increaseScope() {
    scope += 1;
  }
  private void decreaseScope() {
    scope -= 1;
  }

  public void printTokens() {
    int tokensSize = tokens.size();
    for (int i = 0; i < tokensSize; i++) {
      Token token = tokens.get(i);
      if (token.getSymbol() == 43) {
        System.out.println("[ " + sym.terminalNames[token.getSymbol()] + " " + 
          token.getTokenId() + " ] " + token.getSymbolName() + " - Found in symbol table: " + token.getSymbolTable());
      } else {
          System.out.println("[ " + sym.terminalNames[token.getSymbol()] + " ] " + token.getSymbolName());
      } 
    }
  }

  private void writeTokensToFile(String info){
    FileManager fileManager = new FileManager("C:/Users/chris/Documents/NetBeansProjects/CeI-PYI/src/main/java/symbolTable/Tokens.txt");
    fileManager.writeToFile(info);
  }

  private void reportErr(String info, int line, int column) {
    System.err.println("ILLEGAL ENTRY AT LINE " + line + " - COLUMN " + column + " ::> " + yytext());
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { reportErr(yytext(), yyline, yycolumn);
            }
            // fall through
          case 46: break;
          case 2:
            { /* Does nothing */
            }
            // fall through
          case 47: break;
          case 3:
            { saveToken(sym.NOT, yytext()); tokenInfo("-NOT- ", yytext()); return symbol(sym.NOT);
            }
            // fall through
          case 48: break;
          case 4:
            { saveToken(sym.HASH, yytext()); tokenInfo("-HASH- ", yytext()); return symbol(sym.HASH);
            }
            // fall through
          case 49: break;
          case 5:
            { saveToken(sym.AND, yytext()); tokenInfo("-AND- ", yytext()); return symbol(sym.AND);
            }
            // fall through
          case 50: break;
          case 6:
            { saveToken(sym.LPAREN, yytext()); tokenInfo("-LPAREN- ", yytext()); return symbol(sym.LPAREN);
            }
            // fall through
          case 51: break;
          case 7:
            { saveToken(sym.RPAREN, yytext()); tokenInfo("-RPAREN- ", yytext()); return symbol(sym.RPAREN);
            }
            // fall through
          case 52: break;
          case 8:
            { saveToken(sym.MULT, yytext()); tokenInfo("-MULT- ", yytext()); return symbol(sym.MULT);
            }
            // fall through
          case 53: break;
          case 9:
            { saveToken(sym.ADD, yytext()); tokenInfo("-ADD- ", yytext()); return symbol(sym.ADD);
            }
            // fall through
          case 54: break;
          case 10:
            { saveToken(sym.COMMA, yytext()); tokenInfo("-COMMA- ", yytext()); return symbol(sym.COMMA);
            }
            // fall through
          case 55: break;
          case 11:
            { saveToken(sym.SUBS, yytext()); tokenInfo("-SUBS- ", yytext()); return symbol(sym.SUBS);
            }
            // fall through
          case 56: break;
          case 12:
            { saveToken(sym.DOT, yytext()); tokenInfo("-DOT- ", yytext()); return symbol(sym.DOT);
            }
            // fall through
          case 57: break;
          case 13:
            { saveToken(sym.DIV, yytext()); tokenInfo("-DIV- ", yytext()); return symbol(sym.DIV);
            }
            // fall through
          case 58: break;
          case 14:
            { saveToken(sym.INTLIT, yytext()); tokenInfo("-INTEGER- ", yytext()); return symbol(sym.INTLIT);
            }
            // fall through
          case 59: break;
          case 15:
            { saveToken(sym.EQ, yytext()); tokenInfo("-EQ- ", yytext()); return symbol(sym.EQ);
            }
            // fall through
          case 60: break;
          case 16:
            { saveToken(sym.ID, yytext()); return symbol(sym.ID);
            }
            // fall through
          case 61: break;
          case 17:
            { saveToken(sym.LSQUARE, yytext()); tokenInfo("-LSQUARE- ", yytext()); return symbol(sym.LSQUARE);
            }
            // fall through
          case 62: break;
          case 18:
            { saveToken(sym.RSQUARE, yytext()); tokenInfo("-RSQUARE- ", yytext()); return symbol(sym.RSQUARE);
            }
            // fall through
          case 63: break;
          case 19:
            { saveToken(sym.LCURLY, yytext()); tokenInfo("-LCURLY- ", yytext()); return symbol(sym.LCURLY);
            }
            // fall through
          case 64: break;
          case 20:
            { saveToken(sym.OR, yytext()); tokenInfo("-OR- ", yytext()); return symbol(sym.OR);
            }
            // fall through
          case 65: break;
          case 21:
            { saveToken(sym.RCURLY, yytext()); tokenInfo("-RCURLY- ", yytext()); return symbol(sym.RCURLY);
            }
            // fall through
          case 66: break;
          case 22:
            { saveToken(sym.FLOATLIT, yytext()); tokenInfo("-FLOATNUM- ", yytext()); return symbol(sym.FLOATLIT);
            }
            // fall through
          case 67: break;
          case 23:
            { saveToken(sym.EQEQ, yytext()); tokenInfo("-EQEQ- ", yytext()); return symbol(sym.EQEQ);
            }
            // fall through
          case 68: break;
          case 24:
            { saveToken(sym.IF, yytext()); tokenInfo("-IF- ", yytext()); return symbol(sym.IF);
            }
            // fall through
          case 69: break;
          case 25:
            { saveToken(sym.STRINGLIT, yytext()); tokenInfo("-STRING- ", yytext()); return symbol(sym.STRINGLIT);
            }
            // fall through
          case 70: break;
          case 26:
            { saveToken(sym.CHARLIT, yytext()); tokenInfo("-CHAR- ", yytext()); return symbol(sym.CHARLIT);
            }
            // fall through
          case 71: break;
          case 27:
            { saveToken(sym.END, yytext()); tokenInfo("-END- ", yytext()); return symbol(sym.END);
            }
            // fall through
          case 72: break;
          case 28:
            { saveToken(sym.FOR, yytext()); tokenInfo("-FOR- ", yytext()); return symbol(sym.FOR);
            }
            // fall through
          case 73: break;
          case 29:
            { saveToken(sym.INT, yytext()); tokenInfo("-INT- ", yytext()); return symbol(sym.INT);
            }
            // fall through
          case 74: break;
          case 30:
            { tokenInfo("-COMMENT- ", yytext());
            }
            // fall through
          case 75: break;
          case 31:
            { saveToken(sym.CASE, yytext()); tokenInfo("-CASE- ", yytext()); return symbol(sym.CASE);
            }
            // fall through
          case 76: break;
          case 32:
            { saveToken(sym.CHAR, yytext()); tokenInfo("-CHAR- ", yytext()); return symbol(sym.CHAR);
            }
            // fall through
          case 77: break;
          case 33:
            { saveToken(sym.ELSE, yytext()); tokenInfo("-ELSE- ", yytext()); return symbol(sym.ELSE);
            }
            // fall through
          case 78: break;
          case 34:
            { saveToken(sym.THEN, yytext()); tokenInfo("-THEN- ", yytext()); return symbol(sym.THEN);
            }
            // fall through
          case 79: break;
          case 35:
            { saveToken(sym.TRUE, yytext()); tokenInfo("-TRUE- ", yytext()); return symbol(sym.TRUE);
            }
            // fall through
          case 80: break;
          case 36:
            { saveToken(sym.ARRAY, yytext()); tokenInfo("-ARRAY- ", yytext()); return symbol(sym.ARRAY);
            }
            // fall through
          case 81: break;
          case 37:
            { saveToken(sym.BEGIN, yytext()); tokenInfo("-BEGIN- ", yytext()); return symbol(sym.BEGIN);
            }
            // fall through
          case 82: break;
          case 38:
            { saveToken(sym.BREAK, yytext()); tokenInfo("-BREAK- ", yytext()); return symbol(sym.BREAK);
            }
            // fall through
          case 83: break;
          case 39:
            { saveToken(sym.FALSE, yytext()); tokenInfo("-FALSE- ", yytext()); return symbol(sym.FALSE);
            }
            // fall through
          case 84: break;
          case 40:
            { saveToken(sym.FLOAT, yytext()); tokenInfo("-FLOAT- ", yytext()); return symbol(sym.FLOAT);
            }
            // fall through
          case 85: break;
          case 41:
            { saveToken(sym.WHILE, yytext()); tokenInfo("-WHILE- ", yytext()); return symbol(sym.WHILE);
            }
            // fall through
          case 86: break;
          case 42:
            { saveToken(sym.RETURN, yytext()); tokenInfo("-RETURN- ", yytext()); return symbol(sym.RETURN);
            }
            // fall through
          case 87: break;
          case 43:
            { saveToken(sym.STRING, yytext()); tokenInfo("-STRING- ", yytext()); return symbol(sym.STRING);
            }
            // fall through
          case 88: break;
          case 44:
            { saveToken(sym.SWITCH, yytext()); tokenInfo("-SWITCH- ", yytext()); return symbol(sym.SWITCH);
            }
            // fall through
          case 89: break;
          case 45:
            { saveToken(sym.BOOL, yytext()); tokenInfo("-BOOL- ", yytext()); return symbol(sym.BOOL);
            }
            // fall through
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
