
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 34;
  public static final int CHAR = 5;
  public static final int STRINGLIT = 42;
  public static final int CASE = 17;
  public static final int HASH = 21;
  public static final int LPAREN = 24;
  public static final int INT = 2;
  public static final int ARRAY = 7;
  public static final int FOR = 13;
  public static final int RPAREN = 25;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int INTLIT = 39;
  public static final int OR = 37;
  public static final int BOOL = 4;
  public static final int COMMA = 31;
  public static final int DIV = 35;
  public static final int BEGIN = 8;
  public static final int IF = 10;
  public static final int ID = 43;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int LCURLY = 26;
  public static final int ADD = 32;
  public static final int EQEQ = 23;
  public static final int BREAK = 14;
  public static final int FLOATLIT = 40;
  public static final int EQ = 22;
  public static final int SWITCH = 16;
  public static final int RCURLY = 27;
  public static final int CHARLIT = 41;
  public static final int ELSE = 12;
  public static final int LSQUARE = 28;
  public static final int RSQUARE = 29;
  public static final int WHILE = 15;
  public static final int FLOAT = 3;
  public static final int THEN = 11;
  public static final int SUBS = 33;
  public static final int END = 9;
  public static final int STRING = 6;
  public static final int FALSE = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "ARRAY",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "FOR",
  "BREAK",
  "WHILE",
  "SWITCH",
  "CASE",
  "RETURN",
  "TRUE",
  "FALSE",
  "HASH",
  "EQ",
  "EQEQ",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "LSQUARE",
  "RSQUARE",
  "DOT",
  "COMMA",
  "ADD",
  "SUBS",
  "MULT",
  "DIV",
  "AND",
  "OR",
  "NOT",
  "INTLIT",
  "FLOATLIT",
  "CHARLIT",
  "STRINGLIT",
  "ID"
  };
}

