
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHARARR = 9;
  public static final int LTE = 56;
  public static final int MULT = 48;
  public static final int CHAR = 5;
  public static final int STRINGLIT = 32;
  public static final int COMMENT = 26;
  public static final int CASE = 19;
  public static final int LPAREN = 37;
  public static final int HASH = 34;
  public static final int INT = 2;
  public static final int ARRAY = 7;
  public static final int FOR = 15;
  public static final int RPAREN = 38;
  public static final int NOT = 60;
  public static final int AND = 58;
  public static final int LT = 57;
  public static final int INTLIT = 29;
  public static final int OR = 59;
  public static final int COMMA = 44;
  public static final int BOOL = 4;
  public static final int DIV = 49;
  public static final int BEGIN = 10;
  public static final int PADD = 52;
  public static final int MAIN = 22;
  public static final int IF = 12;
  public static final int EXP = 51;
  public static final int ID = 61;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int LCURLY = 39;
  public static final int ADD = 46;
  public static final int EQEQ = 36;
  public static final int MOD = 50;
  public static final int BREAK = 16;
  public static final int EQ = 35;
  public static final int FLOATLIT = 30;
  public static final int GTE = 54;
  public static final int RCURLY = 40;
  public static final int SWITCH = 18;
  public static final int INTARR = 8;
  public static final int CHARLIT = 31;
  public static final int COLON = 45;
  public static final int ELSE = 14;
  public static final int LSQUARE = 41;
  public static final int FUNC = 23;
  public static final int READ = 24;
  public static final int RSQUARE = 42;
  public static final int WHILE = 17;
  public static final int DEFAULT = 20;
  public static final int FLOAT = 3;
  public static final int THEN = 13;
  public static final int SUBS = 47;
  public static final int END = 11;
  public static final int ARRAYLIT = 33;
  public static final int STRING = 6;
  public static final int FALSE = 28;
  public static final int PSUBS = 53;
  public static final int GT = 55;
  public static final int PRINT = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "ARRAY",
  "INTARR",
  "CHARARR",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "FOR",
  "BREAK",
  "WHILE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "RETURN",
  "MAIN",
  "FUNC",
  "READ",
  "PRINT",
  "COMMENT",
  "TRUE",
  "FALSE",
  "INTLIT",
  "FLOATLIT",
  "CHARLIT",
  "STRINGLIT",
  "ARRAYLIT",
  "HASH",
  "EQ",
  "EQEQ",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "LSQUARE",
  "RSQUARE",
  "DOT",
  "COMMA",
  "COLON",
  "ADD",
  "SUBS",
  "MULT",
  "DIV",
  "MOD",
  "EXP",
  "PADD",
  "PSUBS",
  "GTE",
  "GT",
  "LTE",
  "LT",
  "AND",
  "OR",
  "NOT",
  "ID"
  };
}

