
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQ = 3;
  public static final int MULT = 6;
  public static final int error = 1;
  public static final int ADD = 4;
  public static final int SEMI = 2;
  public static final int DIV = 7;
  public static final int SUBS = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "EQ",
  "ADD",
  "SUBS",
  "MULT",
  "DIV"
  };
}

